services:
  app:
    image: amansahni05/url-shortner:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: urlshortner
      DB_USER: postgres
      DB_PASS: mypassword
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    image: amansahni05/url-shortner-nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: urlshortner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

volumes:
  pgdata:
